import numpy as np
# Copyright © 2005-2019, NumPy Developers.

import pandas as pd
# Copyright (c) 2008-2012, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team

def make_ratio(numerator,denumerator):
    ratio = [None]*len(numerator)
    for i in range(len(numerator)):
        if denumerator[i]!=0:
            ratio[i] = numerator[i] / denumerator[i]
        else: #denumerator[i]==0:
            if numerator[i]>0:
                ratio[i] = np.inf
            elif numerator[i]<0:
                ratio[i] = -np.inf
            else: # numerator[i]==0:
                ratio[i] = 0
    return pd.Series(ratio)


def remove_unused_columns(data_loaded,list_of_accounting_columns_to_include):
    # The purpose of this function is to use less computer memory (RAM) by
    # loading only relevant columns in data
    list_of_all_accounting_columns          = get_list_of_all_accounting_columns()
    
    list_of_accounting_columns_to_remove = [i for i in list_of_all_accounting_columns if i not in list_of_accounting_columns_to_include]

    for i in list_of_accounting_columns_to_remove:
        del data_loaded[i]

    return data_loaded

def get_list_of_all_accounting_columns():
    list_of_all_accounting_columns = [
        'EIENDELER',
        'Anleggsmidler',
        'Immaterielle eiendeler',
        'Forskning og utvikling',
        'Konsesjoner, patenter, lisenser, varemerker og lignende rettigheter',
        'Utsatt skattefordel',
        'Goodwill',
        'Oevrige immatrielle eiendeler (jfr. Verdi leiekontrakter m.m.)',
        'Sum immaterielle anleggsmidler',
        'Varige driftsmidler',
        'Tomter, bygninger og annen fast eiendom',
        'Maskiner og anlegg',
        'Skip, rigger, fly og lignende',
        'Driftsloesoere, inventar, verktoey, kontormaskiner og lignende',
        'Oevrige driftsmidler',
        'Sum varige driftsmidler',
        'Finansielle anleggsmidler',
        'Investeringer i datterselskap',
        'Investeringer i annet foretak i samme konsern',
        'Laan til foretak i samme konsern',
        'Investeringer i tilknyttet selskap',
        'Laan til tilknyttet selskap og felles kontrollert virksomhet',
        'Investeringer i aksjer og andeler',
        'Obligasjoner og andre langsiktige fordringer',
        'Sum finansielle anleggsmidler',
        'Sum anleggsmidler',
        'Omloepsmidler',
        'Varer',
        'Raavarer',
        'Varer i arbeid',
        'Ferdigvarer',
        'Fordringer',
        'Kundefordringer',
        'Andre kortsiktige fordringer',
        'Krav paa innbetaling av selskapskapital',
        'Sum fordringer',
        'Investeringer',
        'Aksjer og andeler i samme konsern',
        'Markedsbaserte aksjer',
        'Markedsbaserte obligasjoner',
        'Andre markedsbaserte finansielle instrumenter',
        'Andre kortsiktige finansielle instrumenter',
        'Sum investeringer',
        'Kasse/Bank/Post',
        'Sum omloepsmidler',
        'Sum eiendeler',
        'EGENKAPITAL OG GJELD',
        'Egenkapital',
        'Innskutt egenkapital',
        'Selskapskapital',
        'Egne aksjer',
        'Overkursfond',
        'Annen innskutt egenkapital',
        'Sum innskutt egenkapital',
        'Opptjent egenkapital',
        'Fond for vurderingsforskjeller',
        'Annen egenkapital',
        'Udekket tap',
        'Sum opptjent egenkapital',
        'Sum egenkapital',
        'Minoritetsinteresser* Konsernpost',
        'GJELD',
        'Avsetninger for forpliktelser',
        'Pensjonsforpliktelser',
        'Utsatt skatt',
        'Andre avsetninger for forpliktelser',
        'Sum avsetninger til forpliktelser',
        'Annen langsiktig gjeld',
        'Konvertible laan',
        'Obligasjonslaan',
        'Gjeld til kredittinstitusjoner',
        'Oevrig langsiktig gjeld',
        'Sum langsiktig gjeld',
        'Kortsiktig gjeld',
        'Sertifikatlaan',
        'Leverandoergjeld',
        'Betalbar skatt',
        'Skyldige offentlige utgifter',
        'Utbytte',
        'Annen kortsiktig gjeld',
        'Sum kortsiktig gjeld',
        'Sum egenkapital og gjeld',
        'Salgsinntekter',
        'Honorarer',
        'Offentlig avgift vedr. omsetning (alkoholavg, pant mv)',
        'Offentlig tilskudd/refusjon',
        'Uopptjent inntekt',
        'Annen driftsinntekt',
        'Leieinntekter',
        'Provisjons- og kommisjonsinntekt',
        'Gevinst ved avgang anleggsmidler',
        'Annen driftsrelatert inntekt (inkl. abonnement / reklameinntekter etc.)',
        'Fraktinntekter',
        'Inntekt paa investering i datterselskap',
        'Gevinst ved salg av verdipapirer',
        'Sum driftsinntekter',
        'Endring i beholdning av varer under tilvirkning og ferdig tilvirkede varer',
        'Endring i beholdning av varer under tilvirkning',
        'Endring i beholdning ferdig tilvirkende varer',
        'Beholdningsendring av egentilvirkede anleggsmidler',
        'Varekostnad',
        'Forbruk av raavarer og innkjoepte halvfabrikata',
        'Forbruk av varer under tilvirkning',
        'Forbruk av ferdig tilvirkede varer',
        'Forbruk av innkjoepte varer for videresalg',
        'Fremmedytelse og underentreprise',
        'Annen periodisering',
        'Loennskostnader',
        'Loenn til ansatte',
        'Fordeler i arbeidsforhold',
        'Annen oppgavepliktig godtgjoerelse',
        'Arbeidsgiveravgift og pensjonskostnad',
        'Annen kostnadsgodtgjoerelse',
        'Arbeidsgodtgjoerelse til eiere o.l.',
        'Offentlig tilskudd vedr. arbeidskraft',
        'Offentlig refusjon vedr. arbeidskraft',
        'Annen personalkostnad',
        'Avskrivning paa varige driftsmidler og immaterielle eiendeler',
        'Avskrivninger paa bygninger og annen fast eiendom',
        'Avskrivninger paa transportmidler, maskiner og inventar',
        'Avskriving paa immaterielle eiendeler',
        'Avskriving paa varige driftsmidler og immaterielle eiendeler',
        'Nedskrivning av varige driftsmidler og immaterielle eiendeler',
        'Annen driftskostnad',
        'Tap paa fordring',
        'Frakt',
        'Energi',
        'Kostnad lokaler',
        'Leie maskin, inventar o.l.',
        'Reparasjon og vedlikehold',
        'Kostnader reiser',
        'Forsikringer',
        'Andre driftskostnader (fou kostnader, adm.kostnader, markedsfoeringskostnader)',
        'Sum driftskostnader',
        'Driftsresultat',
        'Konsernbidrag',
        'Resultatandel datterselskap',
        'Inntekt paa investering i annet foretak i samme konsern',
        'Resultatandel annet foretak i samme konsern',
        'Inntekt paa investering i tilknyttet selskap',
        'Resultatandel tilknyttet selskap',
        'Renteinntekter fra foretak i samme konsern',
        'Annen renteinntekt',
        'Renteinntekt skattefri',
        'Annen finansinntekt',
        'Realisert valutagevinster (Agio)',
        'Urealisert valutagevinster (Agio)',
        'Sum finansinntekter',
        'Verdiendring markedsbaserte finansielle omloepsmidler',
        'Verdioekning markedsbaserte finansielle omloepsmidler',
        'Verdireduksjon markedsbaserte finansielle omloepsmidler',
        'Nedskrivning av andre finansielle omloepsmidler',
        'Nedskrivning av finansielle anleggsmidler',
        'Rentekostnader til foretak i samme konsern',
        'Annen rentekostnad',
        'Rentekostnad, ikke fradragsberettiget',
        'Annen finanskostnad',
        'Realisert valutatap (disagio)',
        'Urealisert valutatap (disagio)',
        'Sum finanskostnader',
        'Netto finans',
        'Ordinaert resultat foer skattekostnad',
        'Skattekostnad paa ordinaert resultat',
        'Refusjon skatt etter aksjeloven',
        'Endring utsatt skatt',
        'Ordinaert resultat',
        'Ekstraordinaere inntekter',
        'Ekstraordinaere kostnader',
        'Netto ekstraordinaere poster',
        'Skattekostnad paa ekstraordinaert resultat',
        'Aarsresultat',
        'Overfoeringer og disponeringer',
        'Overfoeringer til/fra fond for vurderingsforskjeller',
        'Avsatt utbytte',
        'Aksjonaerbidrag',
        'Overfoeringer til/fra annen egenkapital',
        'Sum overfoeringer og disponeringer',
        'Sum immaterielle eiendeler',
        'Investering i datterselskap',
        'Investering i annet foretak i samme konsern',
        'Obligasjoner og andre fordringer',
        'Andre fordringer',
        'Konsernfordringer',
        'Aksjer og andeler i foretak i samme konsern',
        'Andre finansielle instrumenter',
        'Bankinnskudd, kontanter og lignende',
        'SUM EIENDELER',
        'Beholdning av egne aksjer',
        'Annen Egenkapital',
        'Minoritetsinteresser',
        'Langsiktig gjeld',
        'Sum avsetninger for forpliktelser',
        'Langsiktig konserngjeld',
        'Ansvarlig laanekapital',
        'Skyldige offentlige avgifter',
        'Kortsiktig konserngjeld',
        'SUM GJELD OG EGENKAPITAL',
        'Poster utenom balansen',
        'Garantistillelser',
        'Pantstillelser',
        'Inntekter',
        'Salgsinntekt',
        'Sum inntekter',
        'Kostnader',
        'Endring i beholdning av egentilvirkede anleggsmidler',
        'Loennskostnad',
        'Sum kostnader',
        'Finansinntekter',
        'Renteinntekt fra foretak i samme konsern',
        'Finanskostnader',
        'Verdiendring av markedsbaserte finansielle omloepsmidler',
        'Rentekostnad til foretak i samme konsern',
        'Ordinaert resultat etter skattekostnad',
        'Ekstraordinaer inntekt',
        'Ekstraordinaer kostnad',
        'Overfoering til/fra fond for vurderingsforskjeller',
        'Fondsemisjon',
        'Andre immaterielle eiendeler',
        'Fond for verdiendringer',
        'Sum gjeld',
        'Resultat av ekstraordinaere poster',
        'Aarsresultat foer minoritetsinteresser',
        'Investeringseiendom',
        'Biologiske eiendeler',
        'Sum varer',
        'Fond for urealiserte gevinster',
        'Sum annen langsiktig gjeld',
        'SUM EGENKAPITAL OG GJELD',
        'POSTER UTENOM BALANSEN',
        'Verdioekning av markedsbaserte finansielle omloepsmidler',
        'Verdioekning andre finansielle instrumenter vurdert til virkelig verdi',
        'Verdireduksjon av markedsbaserte finansielle omloepsmidler',
        'Verdireduksjon andre finansielle instrumenter vurdert til virkelig verdi',
        'Overfoering til/fra fond for urealiserte gevinster',
        'Obligasjoner',
        'Fond',
        'Overfoering til/fra fond',
        'Sum bankinnskudd, kontanter og lignende',
        'Avsetning for forpliktelser',
        'Inntekt paa investering i datterselskap og tilknyttet selskap',
        'Inntekt paa andre investeringer',
        'Nedskrivning av finansielle eiendeler',
        'Ekstraordinaere poster',
        'Konserfordringer',
        'Finansinntekter og finanskostnader',
        'Aarsresultat etter minoritetsinteresser',
        'BALANSE - EIENDELER',
        'BALANSE - EGENKAPITAL OG GJELD',
        'Overkurs',
        'Gjeld',
        'RESULTATREGNSKAP',
        'Andre resultatkomponenter for IFRS-foretak',
        'Totalresultat',
        'Avgitt konsernbidrag',
        'Sum resultatkomponenter for IFRS-foretak',
        'Ordinaert utbytte',
        'Tilleggsutbytte',
        'Ekstraordinaert utbytte',
        'Ikke registrert kapitalforhoeyelse',
        'Skattekostnad paa ekstraordinaere poster',
        ]
    return list_of_all_accounting_columns